name: Fun01 Build

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'fun01/**'

  workflow_dispatch:

env:
  configuration: 'Debug'
  

jobs:
  build:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: fun01
        
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .net Core v3
        uses: actions/setup-dotnet@v1.8.1
        with:
          dotnet-version: '3.1.x'
      - name: Setup .net Core v5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: 'build'
        run: dotnet build --configuration ${{ env.configuration }} --output ./output
      - name: 'test'
        run: dotnet test
      
