name: Web01 Deploy

on:
# make sure to run the action whenever fun01 code is merged to main 
  push:
    branches: [ main ]
    paths:
      - 'web01/**'
      - '!arm/**'
      
# after a deployment, make sure to re-deploy the function again
  workflow_run:
    workflows: ["ARM Deploy"]
    types:
      - completed

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: web01

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js 
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: npm ci
      - run: npm run build-dev
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{secrets.AZURE_SUBSCRIPTION_DEV}}
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
             apiKey=$(az rest --method post --uri /subscriptions/${{secrets.AZURE_SUBSCRIPTIONID}}/resourcegroups/TwVosDevEurRg01/providers/Microsoft.Web/staticSites/TwVosDevEurWeb01/listsecrets?api-version=2020-06-01 --query 'properties.apiKey' -otsv) 
             echo "$apiKey"
             echo "apiKeyStaticWebApp=$apiKey" >> $GITHUB_ENV
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1               
        with:
          azure_static_web_apps_api_token: ${{ env.apiKeyStaticWebApp }}
          action: 'upload'
          ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
          app_location: 'web01/dist' # Application build output generated by a previous step
#           api_location: 'api' # Api source code path - optional
#           output_location: '' # Leave this empty
          skip_app_build: true               
